<?php

use Application\Model\Dto\Rest\ClothingDTOREST;
use Application\Model\Pagination\Page;

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Page<ClothingDTOREST> $clothings
 */

?>

<div id="app" class="container-fluid g-0 mt-5">

  <header class="su-text-container">
      <h1 class="text-center">Second Use</h1>
  </header>

  <main class="container su-product-grid">
    <?php foreach ($clothings->getResults() as $clothing) { 
    /** @var ClothingDTOREST $clothing */  
    ?>
      <a href="<?= $clothing->get_links()['webui'] ?>" class="su-product-card-link">
      <article class="su-product-card" aria-hidden="true">
        <div class="su-product-card-image-container">
          <img 
          src="<?= $clothing->get_expandable()['main_image']; ?>"
          class="" 
          loading="lazy" 
          alt="Product image"
          >
        </div>
        <div class="su-product-card-content">
          <h5 class="su-product-card-title"><?= $clothing->name ?></h5>
          <hr class="d-none d-sm-block my-2">
          <div class="su-product-card-footer">
            <span class="su-product-card-label"><?= $clothing->label ?></span>
            <span class="su-product-card-price"><?= $clothing->price ?></span>
          </div>
        </div>
      </article>
    </a>  
    <?php } ?>
  </main>
</div>