<?php

use Application\Model\Clothing;

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var array<Clothing> $clothings
 */
?>

<main>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Second Use</h1>
      <p class="lead text-body-secondary">This is a small application for testing on an apache server.</p>
    </div>
  </div>
</section>

<div class="position-relative">
  <div class="divider">
    <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
        <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" class="shape-fill"></path>
    </svg>
  </div>
</div>

<div class="bg-primary">
  <div class="container py-10">
    <div id="product-cards" class="row justify-content-md-center"></div>
  </div>
</div>

</main>

<?php $variable = "bar" ?>

<script type="text/javascript">
  var foo = "<?= $this->escapeJs($variable) ?>";
</script>

<?= $this->inlineScript()
  ->appendFile($this->basePath('js/index.js'))
?>