<?php

use Application\Model\Clothing;

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div id="app" class="container-fluid g-0 mt-5 d-flex flex-column gap-5">
  <header class="su-text-container">
    <h1 class="text-center">Second Use</h1>
  </header>
  <main>
    <section class="su-text-container text-center">
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni nesciunt voluptatibus similique deserunt illum facilis aut quibusdam sequi assumenda, quasi quia! Nemo, cupiditate? Saepe fugiat perferendis voluptatibus dolore iure cumque?</p>
    </section>
    <section class="container su-product-grid">
      <div class="card" aria-hidden="true">
        <img src="https://placehold.co/600x400" class="card-img-top" loading="lazy" alt="...">
        <div class="card-body">
          <p class="card-text">text-5</p>
        </div>
      </div>
      <div class="card" aria-hidden="true">
        <img src="https://placehold.co/600x400" class="card-img-top" loading="lazy" alt="...">
        <div class="card-body">
          <p class="card-text">text-5</p>
        </div>
      </div>
      <div class="card" aria-hidden="true">
        <img src="https://placehold.co/600x400" class="card-img-top" loading="lazy" alt="...">
        <div class="card-body">
          <p class="card-text">text-5</p>
        </div>
      </div>
      <div class="card" aria-hidden="true">
        <img src="https://placehold.co/600x400" class="card-img-top" loading="lazy" alt="...">
        <div class="card-body">
          <p class="card-text">text-5</p>
        </div>
      </div>
      <div class="card" aria-hidden="true">
        <img src="https://placehold.co/600x400" class="card-img-top" loading="lazy" alt="...">
        <div class="card-body">
          <p class="card-text">text-5</p>
        </div>
      </div>
      <div class="card" aria-hidden="true">
        <img src="https://placehold.co/600x400" class="card-img-top" loading="lazy" alt="...">
        <div class="card-body">
          <p class="card-text">text-6</p>
        </div>
      </div>
      <div class="card" aria-hidden="true">
        <img src="https://placehold.co/600x400" class="card-img-top" loading="lazy" alt="...">
        <div class="card-body">
          <p class="card-text">text-7</p>
        </div>
      </div>
      <div class="card" aria-hidden="true">
        <img src="https://placehold.co/600x400" class="card-img-top" loading="lazy" alt="...">
        <div class="card-body">
          <p class="card-text">text-8</p>
        </div>
      </div>
    </section>
  </main>
</div>

<?php $variable = "bar" ?>

<script type="text/javascript">
  var foo = "<?= $this->escapeJs($variable) ?>";
</script>

<?= $this->inlineScript()
  ->appendFile($this->basePath('js/index.js'))
?>