volumes:
  postgres-data:
    external: true

services:
  app:
    build: 
      context: .
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    container_name: app-php
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./httpd.conf:/etc/apache2/sites-available/000-default.conf:ro
    depends_on:
    - postgres
  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
  apache_exporter:
    image: lusotycoon/apache-exporter
    container_name: apache_exporter
    restart: always
    ports:
    - '9117:9117/tcp'
    command:
      - '--scrape_uri=http://app/server-status?auto'
      - '--host_override=example.com'
    depends_on:
    - app
  prometheus:
    image: 'prom/prometheus:v2.43.0'
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    depends_on:
      - apache_exporter
