global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "prometheus"
    honor_labels: true
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          alias: 'prometheus'

  - job_name: "apache"
    honor_labels: true
    static_configs:
      - targets: ["app_php:9117"]
        labels:
          alias: 'apache'