global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "prometheus"
    honor_labels: true
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          alias: 'prometheus'

  - job_name: "apache_exporter"
    honor_labels: true
    static_configs:
      - targets: ["apache_exporter:9117"]
        labels:
          alias: 'apache_exporter'
