<?php

use Application\Model\Clothing;

// var_dump($this->url('home')); die;

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var array<Clothing> $clothings
 */
?>
<main>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Album example</h1>
      <p class="lead text-body-secondary">This is a small application for testing on an apache server.</p>
    </div>
  </div>
</section>

<div class="album py-5 bg-body-tertiary">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <?php foreach ($clothings as $clothing) { ?>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
              xmlns="http://www.w3.org/2000/svg"
              role="img" aria-label="Placeholder: Thumbnail"
              preserveAspectRatio="xMidYMid slice" focusable="false">

              <title>Placeholder</title>
              <rect width="100%" height="100%" fill="#55595c"/>
              <text x="50%" y="50%" fill="#eceeef" dy=".3em">
                Thumbnail
              </text>
            </svg>
            <div class="card-body">
              <p class="card-text">
                <span class="badge bg-info text-dark">
                  <?= $clothing->getLabel() ?>
                </span>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      <?php } ?>
    </div>
  </div>
</div>

</main>

<?= $this->inlineScript()
            ->prependFile("public/js/index.js", "text/javascript");
?>

<script type="text/javascript">
    var foo = "<?= $this->escapeJs($variable) ?>";
</script>